import { ServiceOption, ServiceStageOption, AddOnOption, ServiceId } from "./types";

export const SERVICES_DATA: ServiceOption[] = [
  {
    id: "paint_correction",
    name: "Lackkorrektur",
    tagline: "Präzisions-Kratzerentfernung & Spiegelglanz",
    description: "Entfernt Waschstraßenkratzer, Hologramme und Oxidation für maximale Lacktiefe und optische Spiegelklarheit.",
    startingPrice: 349,
    duration: "4 – 12 Std.",
    iconName: "Sparkles",
    popular: true,
    badge: "Beliebt",
  },
  {
    id: "ceramic",
    name: "Keramikversiegelung",
    tagline: "Nano-Glas-Schutz & Extrem Hydrophob",
    description: "Langzeitschutz gegen UV-Strahlung, Baumharz, Vogelkot und Straßenschmutz mit starkem Abperleffekt.",
    startingPrice: 599,
    duration: "1 – 2 Tage",
    iconName: "ShieldCheck",
    badge: "High-End Schutz",
  },
  {
    id: "exterior",
    name: "Außen Aufbereitung",
    tagline: "Handwäsche, Dekontamination & Versiegelung",
    description: "Schonende Handwäsche, Flugrost- & Teerentfernung, Knetbehandlung, Felgentiefenreinigung und Glanzversiegelung.",
    startingPrice: 149,
    duration: "3 – 5 Std.",
    iconName: "Car",
  },
  {
    id: "interior",
    name: "Innen Aufbereitung",
    tagline: "Tiefendampf-Desinfektion & Lederpflege",
    description: "Gründliche Saugarbeit, Heißwasser-Extraktion für Teppiche & Polster, Dampfdesinfektion und Nährpflege für Leder.",
    startingPrice: 129,
    duration: "3 – 5 Std.",
    iconName: "Armchair",
  },
  {
    id: "engine_bay",
    name: "Motorraumreinigung",
    tagline: "Sichere Dampfentfettung & Kunststoffpflege",
    description: "Elektronikschonende Dampfreinigung des Motorraums mit anschließender seidenmatter UV-Kunststoffkonservierung.",
    startingPrice: 79,
    duration: "1 – 2 Std.",
    iconName: "Gauge",
  },
  {
    id: "other",
    name: "Sonderservices",
    tagline: "Individual-Detailing & Spezialbehandlung",
    description: "Maßgeschneiderte Behandlungen wie Farbnebelentfernung, Felgen-Keramik, Matttack-Pflege oder Flottenaufbereitung.",
    startingPrice: 99,
    duration: "Variabel",
    iconName: "Wrench",
  },
];

export const DYNAMIC_QUESTIONS: Record<ServiceId, { title: string; subtitle: string; options: ServiceStageOption[] }> = {
  paint_correction: {
    title: "Wählen Sie die Stufe der Lackkorrektur",
    subtitle: "Wählen Sie die Intensität der Maschinenpolitur je nach Lackzustand.",
    options: [
      {
        id: "paint_single",
        title: "Einstufige Korrektur (Single Stage)",
        description: "Entfernt leichte Swirls und Grauschleier. Steigert den Lackglanz um ca. 60–70%.",
        price: 349,
        durationMinutes: 240,
        features: ["1-Stufen Maschinenpolitur", "Glanz- & Tiefensteigerung", "Ideal für neuwertige Fahrzeuge"],
      },
      {
        id: "paint_two",
        title: "Zweistufige Korrektur (Two Stage)",
        description: "Intensiver Schleifgang gefolgt von einer Hochglanzpolitur. Entfernt bis zu 85–90% aller Defekte.",
        price: 549,
        durationMinutes: 480,
        recommended: true,
        features: ["Defektbeseitigung mit Schleifpaste", "Hochglanz-Finish Politur", "Entfernt tiefe Kratzer & Swirls"],
      },
      {
        id: "paint_three",
        title: "Dreistufige Korrektur (Three Stage)",
        description: "Mehrstufiges Concours-Finishing inklusive Nassschliff einzelner Kratzer für perfekte Spiegelreflexion.",
        price: 899,
        durationMinutes: 720,
        features: ["Mehrstufige Defektkorrektur & Spot-Nassschliff", "Show-Car Spiegelfinish", "95%+ Defektentfernung"],
      },
    ],
  },
  ceramic: {
    title: "Wählen Sie das Keramik-Schutzpaket",
    subtitle: "Wählen Sie die Standzeit und Schutzschichten für Ihren Lack.",
    options: [
      {
        id: "ceramic_1yr",
        title: "1-Jahr HydroShield Keramik",
        description: "Einstiegs-Keramikversiegelung mit extrem glatter Oberfläche und hoher Wasserabweisung für 12 Monate.",
        price: 599,
        durationMinutes: 360,
        features: ["1 Jahr Schutzgarantie", "Extremer Abperleffekt (>110°)", "Inklusive Lackvorbereitung"],
      },
      {
        id: "ceramic_3yr",
        title: "3-Jahre Pro Ceramic Shield",
        description: "Doppelschichtige Hydrophob-Keramikversiegelung für erhöhten chemischen Schutz und UV-Schutz.",
        price: 899,
        durationMinutes: 600,
        recommended: true,
        features: ["3 Jahre Garantie", "9H Härtegrad Schutzschicht", "Beständig gegen Insekten, Teer & Säuren"],
      },
      {
        id: "ceramic_5yr",
        title: "5-Jahre Ultra Graphene Keramik",
        description: "Graphen-verstärkte Versiegelung für maximale Hitzebeständigkeit, Wasserfleckenschutz und Concours-Glanz.",
        price: 1399,
        durationMinutes: 960,
        features: ["5 Jahre Premium Garantie", "Graphen-Multischicht Formel", "Inklusive Scheiben- & Felgenversiegelung"],
      },
    ],
  },
  exterior: {
    title: "Wählen Sie das Außenaufbereitungs-Paket",
    subtitle: "Wählen Sie den Umfang der Lack- und Außenpflege.",
    options: [
      {
        id: "ext_express",
        title: "Express Glanz & Schutz",
        description: "Schonende Handwäsche, Felgenreinigung und 3-Monate Sprühversiegelung.",
        price: 149,
        durationMinutes: 180,
        features: ["Handwäsche & Trocknung", "Reifenpflege & Felgenreinigung", "3 Monate Sprühversiegelung"],
      },
      {
        id: "ext_signature",
        title: "Signature Exterior Detail",
        description: "Inklusive Flugrost-Dekontamination, Knetbehandlung, Tiefenreinigung der Felgenbetten und Keramikversiegelung.",
        price: 249,
        durationMinutes: 300,
        recommended: true,
        features: ["Knetbehandlung & Flugrostentfernung", "Felgenbett- & Bremssattelreinigung", "6 Monate Keramik-Sprühschutz"],
      },
    ],
  },
  interior: {
    title: "Wählen Sie den Umfang der Innenreinigung",
    subtitle: "Maßgeschneiderte Pflege für Polster, Leder und Cockpit.",
    options: [
      {
        id: "int_standard",
        title: "Standard Innenraum-Refresh",
        description: "Gründliches Aussaugen, Cockpit- & Konsolenpflege, Scheibenreinigung und Geruchsneutralisation.",
        price: 129,
        durationMinutes: 180,
        features: ["Komplette Saugarbeit", "Staub- & Fleckenentfernung", "Streifenfreie Scheibenreinigung"],
      },
      {
        id: "int_executive",
        title: "Executive Dampfreinigung & Shampoo",
        description: "Heißwasser-Sprühextraktion für Sitze & Teppiche, Dampfdesinfektion aller Lüftungsschlitze und Lederpflege.",
        price: 229,
        durationMinutes: 300,
        recommended: true,
        features: ["Dampfdesinfektion aller Ritzen & Schlitze", "Sprühextraktions-Polsterreinigung", "Leder-Tiefenpflege & Schutz"],
      },
    ],
  },
  engine_bay: {
    title: "Wählen Sie die Motorraumpflege",
    subtitle: "Schonende Dampfentfettung und Kunststoff-Konservierung.",
    options: [
      {
        id: "eng_standard",
        title: "Standard Dampf & Pflege",
        description: "Sichere Niederdruck-Dampfreinigung der Motoroberflächen mit seidenmatter Versiegelung.",
        price: 79,
        durationMinutes: 90,
        features: ["Schutz empfindlicher Elektronik", "Dampfentfettung", "UV-Kunststoffkonservierung"],
      },
      {
        id: "eng_pro",
        title: "Deep Engine & Ceramic Coat",
        description: "Reinigung der Haubenunterseite, Detail-Entfettung und Hitzebeständige Keramikbeschichtung für Abdeckungen.",
        price: 149,
        durationMinutes: 150,
        recommended: true,
        features: ["Haubenunterseiten-Reinigung", "Hitzebeständige Keramikversiegelung", "Schlauch- & Kabelkonservierung"],
      },
    ],
  },
  other: {
    title: "Wählen Sie den Leistungstyp",
    subtitle: "Spezifizieren Sie Ihre individuellen Anforderungen.",
    options: [
      {
        id: "other_custom",
        title: "Individuelles Wunsch-Detailing",
        description: "Maßgeschneiderte Pflegepakete für Liebhaberfahrzeuge, Oldtimer oder Show-Fahrzeuge.",
        price: 150,
        durationMinutes: 240,
        features: ["Persönliche Beratung", "Individuelle Prozesswahl", "Flexible Terminvergabe"],
      },
      {
        id: "other_fleet",
        title: "Gewerbe- & Fuhrparkservice",
        description: "Spezielle Aufbereitungslösungen für Firmenflotten oder Fahrzeugsammlungen.",
        price: 299,
        durationMinutes: 360,
        features: ["Mengenrabattierte Preisstruktur", "Vor-Ort oder Werkstatt-Service", "Fester Ansprechpartner"],
      },
    ],
  },
};

export const ADDONS_DATA: AddOnOption[] = [
  {
    id: "addon_engine",
    name: "Motorraumreinigung",
    description: "Dampfentfettung und Kunststoffpflege im Motorraum.",
    price: 79,
    durationMinutes: 60,
    iconName: "Gauge",
  },
  {
    id: "addon_ceramic",
    name: "Keramik-Glanzbooster",
    description: "Zusätzliche Opferschicht für noch mehr Glanz und Abperleffekt.",
    price: 149,
    durationMinutes: 45,
    iconName: "ShieldCheck",
    badge: "Beliebt",
  },
  {
    id: "addon_headlight",
    name: "Scheinwerfer-Aufbereitung",
    description: "Nassschliff und Keramikversiegelung für vergilbte Scheinwerfer.",
    price: 89,
    durationMinutes: 60,
    iconName: "Sun",
  },
  {
    id: "addon_glass",
    name: "Scheibenversiegelung",
    description: "Stark wasserabweisende Versiegelung für Windschutzscheibe & Fenster.",
    price: 99,
    durationMinutes: 45,
    iconName: "Sparkles",
  },
  {
    id: "addon_interior_prot",
    name: "Innenraum-Imprägnierung",
    description: "Fleckenabweisender Stoffschutz & UV-Leder-Schutzbarriere.",
    price: 119,
    durationMinutes: 60,
    iconName: "Armchair",
  },
];

export const VEHICLE_SIZES = [
  {
    id: "coupe" as const,
    label: "Kompakt / Coupé",
    subtext: "2-Türer, Kleinwagen, Cabrio",
    multiplier: 1.0,
    icon: "Car",
    example: "Golf, Audi TT, Porsche 911",
  },
  {
    id: "sedan" as const,
    label: "Limousine / Kombi",
    subtext: "4-Türer Limousine, Kombi",
    multiplier: 1.15,
    icon: "CarFront",
    example: "BMW 5er, Mercedes E-Klasse, Passat",
  },
  {
    id: "suv" as const,
    label: "SUV / Geländewagen",
    subtext: "Crossover, 7-Sitzer, Pickup",
    multiplier: 1.35,
    icon: "Truck",
    example: "Porsche Cayenne, BMW X5, GLE",
  },
  {
    id: "exotic" as const,
    label: "Exot / Supercar",
    subtext: "Luxus-Sportwagen oder Carbon-Karosserie",
    multiplier: 1.5,
    icon: "Crown",
    example: "Ferrari, Lamborghini, Rolls Royce",
  },
];

export const TIME_SLOTS = [
  { slot: "08:30", label: "08:30 Uhr", period: "Morning", available: true },
  { slot: "10:00", label: "10:00 Uhr", period: "Morning", available: true },
  { slot: "11:30", label: "11:30 Uhr", period: "Morning", available: false },
  { slot: "13:30", label: "13:30 Uhr", period: "Afternoon", available: true },
  { slot: "15:00", label: "15:00 Uhr", period: "Afternoon", available: true },
  { slot: "16:30", label: "16:30 Uhr", period: "Evening", available: true },
];
