import {
  ServiceOption,
  PackageOption,
  PackageId,
  ServiceId,
  ServiceQuestion,
  AddOnOption,
  IndividualService,
  VehicleOption,
} from "./types";

// ─── Kategorien (ehemals "Services") ─────────────────────────────────────────
export const SERVICES_DATA: ServiceOption[] = [
  {
    id: "exterior",
    name: "Außenreinigung",
    tagline: "Handwäsche · Ton · Versiegelung",
    description: "Gründliche Außenreinigung mit manueller Handwäsche, Tonbehandlung und langlebiger Lackversiegelung.",
    iconName: "Car",
  },
  {
    id: "interior",
    name: "Innenraumreinigung",
    tagline: "Dampf · Leder · Shampoo",
    description: "Tiefenreinigung, Dampfdesinfektion und hochwertige Lederpflege für einen makellosen Innenraum.",
    iconName: "Armchair",
    popular: true,
    badge: "Beliebt",
  },
  {
    id: "full_detail",
    name: "Komplettaufbereitung",
    tagline: "Innen & Außen – alles inklusive",
    description: "Das komplette Erlebnis — vollständige Innen- und Außenaufbereitung in einem einzigen Termin.",
    iconName: "Star",
    badge: "Top-Wert",
  },
  {
    id: "paint_correction",
    name: "Lackaufbereitung",
    tagline: "Maschinenpolitur · Spiegelfinish",
    description: "Mehrstufige Maschinenpolitur zur Beseitigung von Kratzern, Swirl Marks und Oxidation für ein makelloses Finish.",
    iconName: "Sparkles",
    badge: "Premium",
  },
  {
    id: "ceramic",
    name: "Keramikversiegelung",
    tagline: "Nano-Schutz · Hydrophob",
    description: "Professionelle Keramikversiegelung für langfristigen Lackschutz, UV-Beständigkeit und extremen Wasserabperleffekt.",
    iconName: "ShieldCheck",
    badge: "Elite",
  },
];

// ─── Pakete pro Kategorie ────────────────────────────────────────────────────
// Korrekte Reihenfolge: Basic → Deluxe → Premium (keine Duplikate)
export const PACKAGES_DATA: Record<ServiceId, PackageOption[]> = {
  exterior: [
    {
      id: "basic",
      name: "Basic",
      tagline: "Grundlegende Außenwäsche & Reinigung",
      description: "Handwäsche & Trocknung, Felgen- & Reifenreinigung sowie Reifenglanz.",
      price: 70,
      duration: "2–3 Std.",
      features: [
        "Handwäsche & Trocknung",
        "Felgen- & Reifenreinigung",
        "Reifenglanz",
        "Scheibenreinigung",
      ],
    },
    {
      id: "deluxe",
      name: "Deluxe",
      tagline: "Erweiterte Außenreinigung & Pflege",
      description: "Erweiterte Außenaufbereitung inklusive Kunststoffpflege und Lackkonservierung.",
      price: 110,
      duration: "3–4 Std.",
      features: [
        "Handwäsche & Trocknung",
        "Felgen- & Reifenreinigung",
        "Reifenglanz",
        "Scheibenreinigung",
        "Kunststoffpflege",
        "Lackkonservierung",
      ],
      recommended: true,
    },
    {
      id: "premium",
      name: "Premium",
      tagline: "Volle Außenrestaurierung & Schutz",
      description: "Komplette Außenaufbereitung mit Tonbehandlung, Maschinenpolitur und dauerhafter Lackversiegelung.",
      price: 160,
      duration: "5–6 Std.",
      features: [
        "Handwäsche & Trocknung",
        "Tonbehandlung",
        "Felgen- & Reifenreinigung",
        "Reifenglanz",
        "Scheibenreinigung",
        "Kunststoffaufbereitung",
        "Maschinenpolitur (1-Stufe)",
        "Lackversiegelung",
      ],
    },
  ],
  interior: [
    {
      id: "basic",
      name: "Basic",
      tagline: "Schnelle Innenraumauffrischung",
      description: "Komplettes Staubsaugen, Armaturenbrett abwischen und Scheibenreinigung innen.",
      price: 80,
      duration: "2–3 Std.",
      features: [
        "Komplettes Staubsaugen",
        "Armaturenbrett & Mittelkonsole abwischen",
        "Scheibenreinigung innen",
        "Türverkleidungen reinigen",
      ],
    },
    {
      id: "deluxe",
      name: "Deluxe",
      tagline: "Tiefenreinigung & Aufbereitung",
      description: "Tiefenreinigung mit Lederpflege, Textilshampoo und vollständiger Innenaufbereitung.",
      price: 130,
      duration: "3–4 Std.",
      features: [
        "Komplettes Staubsaugen & Absaugen",
        "Reinigung von Armaturenbrett & Konsole",
        "Textilshampoo",
        "Lederpflege",
        "Scheibenreinigung innen",
        "Kofferraum aufbereitung",
      ],
      recommended: true,
    },
    {
      id: "premium",
      name: "Premium",
      tagline: "Premium Innenraumrestaurierung",
      description: "Vollständige Restaurierung mit Dampfreinigung, Lederaufbereitung, Textilversiegelung und Geruchsneutralisierung.",
      price: 200,
      duration: "5–6 Std.",
      features: [
        "Komplettes Staubsaugen & Absaugen",
        "Reinigung von Armaturenbrett & Konsole",
        "Dampfreinigung",
        "Lederpflege & Aufbereitung",
        "Textilversiegelung",
        "Scheibenreinigung innen",
        "Geruchsneutralisierung",
        "Kofferraum aufbereitung",
      ],
    },
  ],
  full_detail: [
    {
      id: "basic",
      name: "Basic",
      tagline: "Komplettpaket Grundreinigung",
      description: "Außenwäsche per Hand, Innenraum aussaugen, Armaturenbrett abwischen und Scheibenreinigung.",
      price: 130,
      duration: "4–5 Std.",
      features: [
        "Außenwäsche per Hand",
        "Felgen & Reifen reinigen",
        "Innenraum aussaugen",
        "Armaturenbrett abwischen",
        "Scheibenreinigung innen & außen",
      ],
    },
    {
      id: "deluxe",
      name: "Deluxe",
      tagline: "Umfassende Innen- & Außenaufbereitung",
      description: "Erweiterte Innen- und Außenreinigung mit Lederpflege, Kunststoffaufbereitung und Lackkonservierung.",
      price: 210,
      duration: "6–7 Std.",
      features: [
        "Komplette Außenreinigung & Trocknung",
        "Felgen- & Reifenreinigung",
        "Kunststoffaufbereitung",
        "Lackkonservierung",
        "Komplette Innenreinigung",
        "Leder-/Stoffbehandlung",
        "Scheibenreinigung innen & außen",
      ],
      recommended: true,
    },
    {
      id: "premium",
      name: "Premium",
      tagline: "Das Komplettpaket für Ihr Fahrzeug",
      description: "Vollständige Fahrzeugtransformation mit Lackpolitur, Dampfreinigung, Lederaufbereitung und Geruchsbeseitigung.",
      price: 320,
      duration: "8–10 Std.",
      features: [
        "Komplette Außenreinigung & Trocknung",
        "Tonbehandlung",
        "Maschinenpolitur (1-Stufe)",
        "Lackversiegelung",
        "Komplette Innenreinigung mit Dampf",
        "Lederaufbereitung",
        "Textilversiegelung",
        "Geruchsbeseitigung",
        "Scheibenreinigung innen & außen",
      ],
    },
  ],
  paint_correction: [
    {
      id: "basic",
      name: "Basic",
      tagline: "Einstufige Politur",
      description: "Einstufige Maschinenpolitur zur Beseitigung leichter Swirl Marks und Glanzverbesserung um 60–70 %.",
      price: 349,
      duration: "4–5 Std.",
      features: [
        "1-stufige Maschinenpolitur",
        "Beseitigung leichter Swirl Marks",
        "Glanzverbesserung",
        "Ideal für gut gepflegten Lack",
      ],
    },
    {
      id: "deluxe",
      name: "Deluxe",
      tagline: "Zweistufige Korrektur",
      description: "Schnittpoliermittel gefolgt von Hochglanzpolitur — beseitigt bis zu 85 % der Lackfehler.",
      price: 549,
      duration: "7–9 Std.",
      features: [
        "Schnittpolierstufe",
        "Hochglanzpolitur",
        "Beseitigung tiefer Swirl Marks & Kratzer",
        "Lackdekontaminierung inklusive",
      ],
      recommended: true,
    },
    {
      id: "premium",
      name: "Premium",
      tagline: "Concours-Finish",
      description: "Mehrstufige Korrektur inkl. punktuellem Nassschliff für ein Spiegelfinish mit 95 %+ Fehlerbeseitigung.",
      price: 899,
      duration: "10–14 Std.",
      features: [
        "Mehrstufige Politur",
        "Punktueller Nassschliff",
        "95 %+ Fehlerbeseitigung",
        "Showcar-Spiegelreflexion",
      ],
    },
  ],
  ceramic: [
    {
      id: "basic",
      name: "Basic",
      tagline: "1-Jahres-Schutz",
      description: "Einstiegs-Keramikversiegelung mit extremem Hydrophob-Effekt für 12 Monate.",
      price: 599,
      duration: "5–6 Std.",
      features: [
        "1-Jahr Schutzgarantie",
        "Kontaktwinkel > 110°",
        "Lackvorbehandlung inklusive",
        "Pflege-Kit inklusive",
      ],
    },
    {
      id: "deluxe",
      name: "Deluxe",
      tagline: "3-Jahres-Profi",
      description: "Zweilagen-9H-Keramikversiegelung für überlegene Chemikalienbeständigkeit und UV-Schutz.",
      price: 899,
      duration: "8–10 Std.",
      features: [
        "3-Jahre Garantie",
        "9H-Härteschicht",
        "Chemikalien- & UV-Beständigkeit",
        "Felgenversiegelung inklusive",
      ],
      recommended: true,
    },
    {
      id: "premium",
      name: "Premium",
      tagline: "5-Jahres-Graphen-Schutz",
      description: "Graphen-verstärkte Mehrlagenversiegelung für maximale Hitzebeständigkeit und dauerhaften Glanz.",
      price: 1399,
      duration: "12–14 Std.",
      features: [
        "5-Jahre Premium-Garantie",
        "Graphen-Mehrlagenformel",
        "Hitze- & Wasserflecken-Beständigkeit",
        "Glas- & Felgenversiegelung inklusive",
      ],
    },
  ],
};

// ─── Einzelleistungen ────────────────────────────────────────────────────────
export const INDIVIDUAL_SERVICES: IndividualService[] = [
  {
    id: "innenraumreinigung",
    name: "Innenraumreinigung",
    description: "Gründliche Reinigung des gesamten Fahrzeuginnenraums inkl. Staubsaugen, Wischen und Scheibenreinigung innen.",
    price: 80,
    duration: "2–3 Std.",
    iconName: "Armchair",
    badge: "Beliebt",
  },
  {
    id: "aussenreinigung",
    name: "Außenreinigung",
    description: "Manuelle Handwäsche, Felgen- & Reifenreinigung sowie Scheibenreinigung außen.",
    price: 70,
    duration: "1–2 Std.",
    iconName: "Car",
  },
  {
    id: "lackpolitur",
    name: "Lackpolitur",
    description: "Einstufige Maschinenpolitur zur Beseitigung leichter Kratzer und Swirl Marks.",
    price: 180,
    duration: "3–4 Std.",
    iconName: "Sparkles",
  },
  {
    id: "keramikversiegelung",
    name: "Keramikversiegelung",
    description: "Professionelle Keramikversiegelung für dauerhaften Lackschutz und Hydrophob-Effekt.",
    price: 599,
    duration: "5–6 Std.",
    iconName: "ShieldCheck",
    badge: "Elite",
  },
  {
    id: "motorraumreinigung",
    name: "Motorraumreinigung",
    description: "Gründliche Reinigung und Pflege des Motorraums für ein makelloses Erscheinungsbild.",
    price: 85,
    duration: "1–2 Std.",
    iconName: "Gauge",
  },
  {
    id: "glasreinigung",
    name: "Glasreinigung",
    description: "Professionelle Reinigung aller Scheiben innen und außen für streifenfreie Klarheit.",
    price: 45,
    duration: "45–60 Min.",
    iconName: "Droplets",
  },
  {
    id: "felgenreinigung",
    name: "Felgenreinigung",
    description: "Tiefenreinigung aller Felgen zur Beseitigung von Bremsenstaub und Straßenschmutz.",
    price: 50,
    duration: "45–60 Min.",
    iconName: "Circle",
  },
  {
    id: "snow_foam_wash",
    name: "Snow Foam Wash",
    description: "Schonende Vorwäsche mit Schneeschaum für schmutzlösende und lackschonende Reinigung.",
    price: 35,
    duration: "30–45 Min.",
    iconName: "Wind",
  },
];

// ─── Fahrzeugoptionen ────────────────────────────────────────────────────────
export const VEHICLE_OPTIONS: VehicleOption[] = [
  {
    id: "sedan",
    name: "Limousine / Kompakt",
    description: "Kleinwagen, Limousinen & Kombis bis 4,7 m",
    iconName: "vehicle-sedan",
    surcharge: 0,
  },
  {
    id: "suv",
    name: "SUV / Geländewagen",
    description: "Kompakt-SUVs, mittelgroße & große SUVs",
    iconName: "vehicle-suv",
    surcharge: 20,
  },
  {
    id: "van",
    name: "Van / Transporter",
    description: "Minivans, Vans & leichte Transporter",
    iconName: "vehicle-van",
    surcharge: 30,
  },
  {
    id: "coupe",
    name: "Coupé / Cabrio / Sportwagen",
    description: "Zweitürige Coupés, Cabriolets & Sportwagen",
    iconName: "vehicle-coupe",
    surcharge: 0,
  },
  {
    id: "pickup",
    name: "Pickup / Offroader",
    description: "Pickups, große Geländefahrzeuge & Trucks",
    iconName: "vehicle-suv",
    surcharge: 40,
  },
];

// ─── Service-spezifische Fragen ───────────────────────────────────────────────
export const SERVICE_QUESTIONS: Record<ServiceId, ServiceQuestion[]> = {
  exterior: [
    {
      id: "ext_condition",
      question: "Wie ist der Zustand des Lacks?",
      iconName: "Search",
      options: [
        { id: "good", label: "Gut — leichte Swirl Marks", iconName: "CheckCircle" },
        { id: "moderate", label: "Mittel — sichtbare Kratzer", iconName: "AlertCircle" },
        { id: "poor", label: "Schlecht — starke Oxidation", iconName: "XCircle" },
      ],
    },
    {
      id: "ext_coating",
      question: "Vorhandene Versiegelung oder Wachs?",
      iconName: "Layers",
      options: [
        { id: "none", label: "Keine", iconName: "X" },
        { id: "wax", label: "Wachs / Versiegelung", iconName: "Droplets" },
        { id: "ceramic", label: "Keramikversiegelung", iconName: "ShieldCheck" },
      ],
    },
  ],
  interior: [
    {
      id: "int_pet",
      question: "Tierhaare vorhanden?",
      iconName: "Dog",
      options: [
        { id: "no", label: "Nein", iconName: "X" },
        { id: "light", label: "Wenig", iconName: "Minus" },
        { id: "heavy", label: "Stark — Hund / Katze", iconName: "AlertCircle" },
      ],
    },
    {
      id: "int_leather",
      question: "Sitzmaterial?",
      iconName: "Armchair",
      options: [
        { id: "fabric", label: "Stoff", iconName: "Layers" },
        { id: "leather", label: "Leder", iconName: "Star" },
        { id: "alcantara", label: "Alcantara / Wildleder", iconName: "Sparkles" },
      ],
    },
  ],
  full_detail: [
    {
      id: "full_pet",
      question: "Tierhaare vorhanden?",
      iconName: "Dog",
      options: [
        { id: "no", label: "Nein", iconName: "X" },
        { id: "yes", label: "Ja", iconName: "AlertCircle" },
      ],
    },
    {
      id: "full_paint",
      question: "Lackzustand?",
      iconName: "Search",
      options: [
        { id: "good", label: "Gut", iconName: "CheckCircle" },
        { id: "moderate", label: "Mittelmäßig — Swirl Marks", iconName: "AlertCircle" },
        { id: "poor", label: "Schlecht — Korrektur nötig", iconName: "XCircle" },
      ],
    },
  ],
  paint_correction: [
    {
      id: "pc_type",
      question: "Hauptfehlertyp?",
      iconName: "Sparkles",
      options: [
        { id: "swirls", label: "Swirl Marks", iconName: "Circle" },
        { id: "scratches", label: "Tiefe Kratzer", iconName: "Minus" },
        { id: "oxidation", label: "Oxidation / Verblassung", iconName: "Sun" },
      ],
    },
    {
      id: "pc_coated",
      question: "Vorherige Keramikversiegelung?",
      iconName: "ShieldCheck",
      options: [
        { id: "no", label: "Keine Versiegelung", iconName: "X" },
        { id: "yes", label: "Ja — Entfernung nötig", iconName: "CheckCircle" },
        { id: "unsure", label: "Nicht sicher", iconName: "HelpCircle" },
      ],
    },
  ],
  ceramic: [
    {
      id: "cer_new",
      question: "Fahrzeugzustand?",
      iconName: "Car",
      options: [
        { id: "new", label: "Neu / Neuwertig", iconName: "Sparkles" },
        { id: "corrected", label: "Lack korrigiert", iconName: "CheckCircle" },
        { id: "daily", label: "Alltäglicher Gebrauch", iconName: "Car" },
      ],
    },
    {
      id: "cer_previous",
      question: "Vorhandene Versiegelung?",
      iconName: "Layers",
      options: [
        { id: "none", label: "Keine frühere Versiegelung", iconName: "X" },
        { id: "expired", label: "Abgelaufene Versiegelung", iconName: "Clock" },
        { id: "active", label: "Aktive Versiegelung", iconName: "ShieldCheck" },
      ],
    },
  ],
};

// ─── Zusatzleistungen (Add-ons) ───────────────────────────────────────────────
export const ADDONS_DATA: AddOnOption[] = [
  {
    id: "addon_headlight",
    name: "Scheinwerfer-Aufbereitung",
    description: "Kristallklare Sicht durch professionelle Scheinwerferpolierung.",
    price: 90,
    iconName: "Lightbulb",
    badge: "Beliebt",
  },
  {
    id: "addon_pet_hair",
    name: "Tierhaar-Entfernung",
    description: "Gründliche Entfernung von Tierhaaren aus dem gesamten Innenraum.",
    price: 40,
    iconName: "Wind",
  },
  {
    id: "addon_odour",
    name: "Geruchs-Neutralisierung",
    description: "Professionelle Beseitigung unerwünschter Gerüche durch Ozonbehandlung.",
    price: 110,
    iconName: "Sparkles",
  },
  {
    id: "addon_interior_prot",
    name: "Innenraum-Versiegelung",
    description: "Fleckenabweisender Schutz vor UV-Schäden für Stoff und Kunststoff.",
    price: 150,
    iconName: "ShieldCheck",
  },
  {
    id: "addon_glass",
    name: "Windschutzscheiben-Versiegelung",
    description: "Regenabweisender Schutz für klare Sicht bei jedem Wetter.",
    price: 100,
    iconName: "Droplets",
  },
  {
    id: "addon_engine",
    name: "Motorraum-Reinigung",
    description: "Detaillierte Reinigung und Pflege des Motorraums.",
    price: 85,
    iconName: "Gauge",
  },
  {
    id: "addon_wheel_ceramic",
    name: "Felgen-Keramikversiegelung",
    description: "Langlebiger Schutz gegen Bremsstaub und Korrosion.",
    price: 120,
    iconName: "Circle",
    badge: "Pro 4 Felgen",
  },
  {
    id: "addon_scratch",
    name: "Steinschlag-Ausbesserung",
    description: "Reparatur von Steinschlägen und tiefen Kratzern im Lack.",
    price: 50,
    iconName: "Wrench",
    badge: "Ab 50 €",
  },
];

// ─── Zeitslots ────────────────────────────────────────────────────────────────
export const TIME_SLOTS = [
  { slot: "08:00", period: "Morgen", available: true },
  { slot: "09:30", period: "Morgen", available: true },
  { slot: "11:00", period: "Morgen", available: false },
  { slot: "13:00", period: "Nachmittag", available: true },
  { slot: "14:30", period: "Nachmittag", available: true },
  { slot: "16:00", period: "Nachmittag", available: true },
  { slot: "17:30", period: "Abend", available: false },
];
