import { ServiceOption, ServiceStageOption, AddOnOption, ServiceId, VehicleSizeCategory } from "./types";

export const SERVICES_DATA: ServiceOption[] = [
  {
    id: "exterior",
    name: "Exterior Detail",
    tagline: "Handwash · Decontamination · Sealant",
    description: "Careful hand wash, iron fallout & tar removal, clay bar treatment, wheel deep-clean and gloss sealant.",
    startingPrice: 149,
    duration: "3 – 5 hrs",
    iconName: "Car",
  },
  {
    id: "interior",
    name: "Interior Detail",
    tagline: "Steam Disinfection · Leather Care",
    description: "Deep vacuuming, hot-water extraction for seats & carpets, steam disinfection and premium leather conditioning.",
    startingPrice: 129,
    duration: "3 – 5 hrs",
    iconName: "Armchair",
  },
  {
    id: "interior_exterior",
    name: "Interior + Exterior",
    tagline: "Complete Head-to-Toe Treatment",
    description: "The full WV experience — a thorough interior detail combined with a complete exterior decontamination and protection.",
    startingPrice: 249,
    duration: "6 – 9 hrs",
    iconName: "Star",
    popular: true,
    badge: "Most Popular",
  },
  {
    id: "paint_correction",
    name: "Paint Correction",
    tagline: "Precision Scratch Removal · Mirror Finish",
    description: "Machine polishing removes wash swirls, holograms and oxidation — restoring maximum depth and optical clarity.",
    startingPrice: 349,
    duration: "4 – 12 hrs",
    iconName: "Sparkles",
    badge: "Premium",
  },
  {
    id: "ceramic",
    name: "Ceramic Coating",
    tagline: "Nano-Glass Protection · Hydrophobic",
    description: "Long-term protection against UV, tree resin, bird droppings and road grime with an extreme beading effect.",
    startingPrice: 599,
    duration: "1 – 2 days",
    iconName: "ShieldCheck",
    badge: "Elite",
  },
];

export const DYNAMIC_QUESTIONS: Record<ServiceId, { title: string; subtitle: string; options: ServiceStageOption[] }> = {
  paint_correction: {
    title: "Select Paint Correction Intensity",
    subtitle: "Choose the level of machine polishing based on your paint condition.",
    options: [
      {
        id: "paint_single",
        title: "Single Stage Correction",
        description: "Removes light swirls and grey haze. Boosts gloss by approximately 60–70%.",
        price: 349,
        durationMinutes: 240,
        features: ["1-stage machine polish", "Gloss & depth enhancement", "Ideal for near-new vehicles"],
      },
      {
        id: "paint_two",
        title: "Two Stage Correction",
        description: "Intensive cutting stage followed by a high-gloss polish. Removes up to 85–90% of all defects.",
        price: 549,
        durationMinutes: 480,
        recommended: true,
        features: ["Defect removal with compound", "High-gloss finishing polish", "Removes deep scratches & swirls"],
      },
      {
        id: "paint_three",
        title: "Three Stage Correction",
        description: "Multi-stage Concours finishing including wet sanding of individual scratches for a perfect mirror reflection.",
        price: 899,
        durationMinutes: 720,
        features: ["Multi-stage defect correction & spot wet-sanding", "Show-car mirror finish", "95%+ defect removal"],
      },
    ],
  },
  ceramic: {
    title: "Select Ceramic Protection Package",
    subtitle: "Choose durability and coating layers for your paintwork.",
    options: [
      {
        id: "ceramic_1yr",
        title: "1-Year HydroShield Ceramic",
        description: "Entry-level ceramic coating with an ultra-smooth surface and high water repellency for 12 months.",
        price: 599,
        durationMinutes: 360,
        features: ["1-year protection guarantee", "Extreme beading effect (>110°)", "Includes paint prep"],
      },
      {
        id: "ceramic_3yr",
        title: "3-Year Pro Ceramic Shield",
        description: "Dual-layer hydrophobic ceramic coating for enhanced chemical resistance and UV protection.",
        price: 899,
        durationMinutes: 600,
        recommended: true,
        features: ["3-year guarantee", "9H hardness protection layer", "Resistant to insects, tar & acids"],
      },
      {
        id: "ceramic_5yr",
        title: "5-Year Ultra Graphene Ceramic",
        description: "Graphene-enhanced coating for maximum heat resistance, water spot protection and Concours gloss.",
        price: 1399,
        durationMinutes: 960,
        features: ["5-year premium guarantee", "Graphene multi-layer formula", "Includes glass & wheel coating"],
      },
    ],
  },
  exterior: {
    title: "Select Exterior Detail Package",
    subtitle: "Choose the scope of paint and exterior care.",
    options: [
      {
        id: "ext_express",
        title: "Express Gloss & Protect",
        description: "Gentle hand wash, wheel clean and 3-month spray sealant.",
        price: 149,
        durationMinutes: 180,
        features: ["Hand wash & blow-dry", "Tyre dressing & wheel clean", "3-month spray sealant"],
      },
      {
        id: "ext_signature",
        title: "Signature Exterior Detail",
        description: "Includes iron fallout decontamination, clay bar, wheel barrel deep-clean and ceramic spray protection.",
        price: 249,
        durationMinutes: 300,
        recommended: true,
        features: ["Clay bar & iron fallout removal", "Wheel barrel & brake caliper clean", "6-month ceramic spray protection"],
      },
    ],
  },
  interior: {
    title: "Select Interior Cleaning Scope",
    subtitle: "Tailored care for upholstery, leather and cockpit.",
    options: [
      {
        id: "int_standard",
        title: "Standard Interior Refresh",
        description: "Deep vacuum, cockpit & console care, glass cleaning and odour neutralisation.",
        price: 129,
        durationMinutes: 180,
        features: ["Full vacuum", "Dust & stain removal", "Streak-free glass cleaning"],
      },
      {
        id: "int_executive",
        title: "Executive Steam & Shampoo",
        description: "Hot-water extraction for seats & carpets, steam disinfection of all vents and premium leather care.",
        price: 229,
        durationMinutes: 300,
        recommended: true,
        features: ["Steam disinfection of all gaps & vents", "Extraction shampoo upholstery", "Premium leather conditioning"],
      },
    ],
  },
  interior_exterior: {
    title: "Select Complete Detail Package",
    subtitle: "Full interior and exterior treatment in one appointment.",
    options: [
      {
        id: "combo_standard",
        title: "Complete Standard Detail",
        description: "Hand wash, clay bar, interior vacuum, cockpit care and 3-month spray sealant.",
        price: 249,
        durationMinutes: 360,
        features: ["Full hand wash & clay bar", "Interior vacuum & wipe-down", "3-month exterior sealant"],
      },
      {
        id: "combo_signature",
        title: "Signature Full Detail",
        description: "Deep exterior decontamination combined with executive steam cleaning and premium leather care.",
        price: 399,
        durationMinutes: 540,
        recommended: true,
        features: ["Iron fallout & clay bar", "Hot-water extraction & steam disinfection", "Leather conditioning & 6-month protection"],
      },
    ],
  },
  engine_bay: {
    title: "Select Engine Bay Care",
    subtitle: "Safe steam degreasing and plastic conditioning.",
    options: [
      {
        id: "eng_standard",
        title: "Standard Steam & Dress",
        description: "Safe low-pressure steam cleaning of engine surfaces with a satin-matt sealant.",
        price: 79,
        durationMinutes: 90,
        features: ["Electronics-safe protection", "Steam degreasing", "UV plastic conditioning"],
      },
      {
        id: "eng_pro",
        title: "Deep Engine & Ceramic Coat",
        description: "Bonnet underside cleaning, detail degreasing and heat-resistant ceramic coating on covers.",
        price: 149,
        durationMinutes: 150,
        recommended: true,
        features: ["Bonnet underside cleaning", "Heat-resistant ceramic coating", "Hose & cable conditioning"],
      },
    ],
  },
  other: {
    title: "Select Service Type",
    subtitle: "Specify your individual requirements.",
    options: [
      {
        id: "other_custom",
        title: "Custom Detailing",
        description: "Bespoke treatment packages for collector vehicles, classics or show cars.",
        price: 150,
        durationMinutes: 240,
        features: ["Personal consultation", "Individual process selection", "Flexible scheduling"],
      },
      {
        id: "other_fleet",
        title: "Corporate Fleet Service",
        description: "Specialist detailing solutions for company fleets or vehicle collections.",
        price: 299,
        durationMinutes: 360,
        features: ["Volume discount pricing", "On-site or workshop service", "Dedicated point of contact"],
      },
    ],
  },
};

export const ADDONS_DATA: AddOnOption[] = [
  {
    id: "addon_engine",
    name: "Engine Bay Cleaning",
    description: "Steam degreasing and plastic conditioning inside the engine bay.",
    price: 79,
    durationMinutes: 60,
    iconName: "Gauge",
  },
  {
    id: "addon_pethair",
    name: "Pet Hair Removal",
    description: "Specialist extraction and rubber-blade removal of embedded pet hair from all upholstery.",
    price: 59,
    durationMinutes: 45,
    iconName: "Dog",
    badge: "Popular",
  },
  {
    id: "addon_headlight",
    name: "Headlight Restoration",
    description: "Wet-sand and ceramic seal yellowed headlights to OEM clarity.",
    price: 89,
    durationMinutes: 60,
    iconName: "Sun",
  },
  {
    id: "addon_odor",
    name: "Odor Removal",
    description: "Ozone treatment and deep-clean to permanently eliminate smoke, food and pet odours.",
    price: 69,
    durationMinutes: 60,
    iconName: "Wind",
  },
  {
    id: "addon_glass",
    name: "Glass Coating",
    description: "Strongly water-repellent coating for windscreen and all windows.",
    price: 99,
    durationMinutes: 45,
    iconName: "Sparkles",
  },
  {
    id: "addon_wheel_ceramic",
    name: "Wheel Ceramic Coating",
    description: "Ceramic protection on all four wheels — resists brake dust and road grime.",
    price: 129,
    durationMinutes: 60,
    iconName: "Circle",
    badge: "New",
  },
  {
    id: "addon_interior_prot",
    name: "Interior Protection",
    description: "Stain-repellent fabric protection and UV leather barrier.",
    price: 119,
    durationMinutes: 60,
    iconName: "Armchair",
  },
];

export const VEHICLE_SIZES: { id: VehicleSizeCategory; label: string; subtext: string; multiplier: number; icon: string; example: string }[] = [
  {
    id: "coupe",
    label: "Coupe",
    subtext: "2-door, hatchback, convertible",
    multiplier: 1.0,
    icon: "Car",
    example: "Golf, Audi TT, Porsche 911",
  },
  {
    id: "sedan",
    label: "Sedan",
    subtext: "4-door saloon, estate",
    multiplier: 1.15,
    icon: "CarFront",
    example: "BMW 5 Series, E-Class, Passat",
  },
  {
    id: "suv",
    label: "SUV",
    subtext: "Crossover, 4x4, pickup",
    multiplier: 1.35,
    icon: "Truck",
    example: "Porsche Cayenne, BMW X5, GLE",
  },
  {
    id: "van",
    label: "Van",
    subtext: "Minivan, MPV, large commercial",
    multiplier: 1.5,
    icon: "Bus",
    example: "VW Transporter, Mercedes Vito",
  },
];

export const TIME_SLOTS = [
  { slot: "08:30", label: "08:30", period: "Morning", available: true },
  { slot: "10:00", label: "10:00", period: "Morning", available: true },
  { slot: "11:30", label: "11:30", period: "Morning", available: false },
  { slot: "13:30", label: "13:30", period: "Afternoon", available: true },
  { slot: "15:00", label: "15:00", period: "Afternoon", available: true },
  { slot: "16:30", label: "16:30", period: "Evening", available: true },
];
